### ISSUE TITLE
17. Split domain model using bounded contexts

### ISSUE THREAD

**Issue by sergey-morenets** [jakubgrajber/Banking-System-Demo#17]

**Comment by jakubgrajber** [comment]
I separated the registration and notifications contexts

**Comment by sergey-morenets** [comment]
Hi

The main idea of this task was to define bounded contexts for your domain model and split domain model. You have two have microservices now (user and notifications) and notification microservice doesn't have any domain model, it's just infrastructure service. So please, reopen this task and close it once you'll have domain model in each microservice

**Comment by jakubgrajber** [comment]
I added transactions and bank-account microservice with domain model
