### ISSUE TITLE
2. Domain model

### ISSUE THREAD

**Issue by sergey-morenets** [jakubgrajber/Banking-System-Demo#2]

**Comment by sergey-morenets** [comment]
Hi

Why did you close this task? In your README you wrote that your application shoud deal with payments, transactions and accounts. I don't see any of the entities in your domain model. So please, reopen this ticket and close it once you finish your domain model.

**Comment by jakubgrajber** [comment]
Hi @sergey-morenets 

Okay, I will work on this.

**Comment by jakubgrajber** [comment]
I added User and BankAccount domain models today. Actually, I have 3 concrete classes which inherit from BankAccount, but I developed CheckingBankAccount so far. I have to also implement domain model for transactions
