### ISSUE TITLE
20. Create events for notifications between microservices

### ISSUE THREAD

**Issue by sergey-morenets** [jakubgrajber/Banking-System-Demo#20]

**Comment by jakubgrajber** [comment]
I created event notification between user and notifications microservices using Kafka

**Comment by sergey-morenets** [comment]
Why do you have UserRegisteredEvent class in both microservices? It should be located in the client library. Please, reopen this task and close it once you finish the transition.

**Comment by jakubgrajber** [comment]
I added user-client library
